name: build_doco

on:
  workflow_dispatch:
      branches: [ main ]
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
        - uses: actions/setup-python@v2
        - uses: actions/checkout@master
          with:
            fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
        - name: Build and Commit
          uses: sphinx-notes/pages@v2
          with:
            documentation_path: ./doco
            requirements_path: ./requirements-docs.txt
        - name: Push changes
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: gh-pages
